language: rust
rust: stable
sudo: false
dist: trusty

cache:
  directories:
    - $HOME/.yarn-cache

before_install:
  - nvm install 6.10.0
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - npm config set spin false
  - npm install -g yarn

install:
  - yarn
  - yarn run bower install

script:
  - yarn run test
